# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Modern, maintained replacement for ls
brew "eza"
# Utility to determine file types
brew "file-formula"
# Distributed revision control system
brew "git"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Theme for zsh
brew "powerlevel10k"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Vi 'workalike' with many additional features
brew "vim"
# JavaScript toolchain manager for reproducible environments
brew "volta"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
